# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dmp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.page_1)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.page_1)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.RobotIPLabel = QtWidgets.QLabel(self.splitter)
        self.RobotIPLabel.setObjectName("RobotIPLabel")
        self.IPLineEdit = QtWidgets.QLineEdit(self.splitter)
        self.IPLineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.IPLineEdit.setObjectName("IPLineEdit")
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.simulationCheckBox = QtWidgets.QCheckBox(self.splitter_2)
        self.simulationCheckBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.simulationCheckBox.setObjectName("simulationCheckBox")
        self.gridLayout_4.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(100, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setMinimumSize(QtCore.QSize(0, 70))
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.shutDownButton = QtWidgets.QPushButton(self.frame)
        self.shutDownButton.setObjectName("shutDownButton")
        self.verticalLayout.addWidget(self.shutDownButton)
        self.gridLayout_5.addWidget(self.frame, 2, 0, 1, 1)
        self.ChooseRobotcomboBox = QtWidgets.QComboBox(self.frame_3)
        self.ChooseRobotcomboBox.setObjectName("ChooseRobotcomboBox")
        self.ChooseRobotcomboBox.addItem("")
        self.ChooseRobotcomboBox.addItem("")
        self.ChooseRobotcomboBox.addItem("")
        self.gridLayout_5.addWidget(self.ChooseRobotcomboBox, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_21 = QtWidgets.QFrame(self.page_2)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.splitter_12 = QtWidgets.QSplitter(self.frame_21)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.Tab = QtWidgets.QTabWidget(self.splitter_12)
        self.Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tab.setObjectName("Tab")
        self.Recording_tab = QtWidgets.QWidget()
        self.Recording_tab.setObjectName("Recording_tab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.Recording_tab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_22 = QtWidgets.QFrame(self.Recording_tab)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.start_recording_button = QtWidgets.QPushButton(self.frame_22)
        self.start_recording_button.setMinimumSize(QtCore.QSize(0, 50))
        self.start_recording_button.setObjectName("start_recording_button")
        self.verticalLayout_11.addWidget(self.start_recording_button)
        self.stop_recording_button = QtWidgets.QPushButton(self.frame_22)
        self.stop_recording_button.setMinimumSize(QtCore.QSize(0, 50))
        self.stop_recording_button.setObjectName("stop_recording_button")
        self.verticalLayout_11.addWidget(self.stop_recording_button)
        self.gridLayout_19.addWidget(self.frame_22, 2, 1, 1, 4)
        self.frame_23 = QtWidgets.QFrame(self.Recording_tab)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.rec_EE_radio_button = QtWidgets.QRadioButton(self.frame_23)
        self.rec_EE_radio_button.setObjectName("rec_EE_radio_button")
        self.verticalLayout_12.addWidget(self.rec_EE_radio_button)
        self.rec_JS_radio_button = QtWidgets.QRadioButton(self.frame_23)
        self.rec_JS_radio_button.setObjectName("rec_JS_radio_button")
        self.verticalLayout_12.addWidget(self.rec_JS_radio_button)
        self.rec_JS_Filter_radio_button = QtWidgets.QRadioButton(self.frame_23)
        self.rec_JS_Filter_radio_button.setObjectName("rec_JS_Filter_radio_button")
        self.verticalLayout_12.addWidget(self.rec_JS_Filter_radio_button)
        self.gridLayout_19.addWidget(self.frame_23, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.Recording_tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_19.addWidget(self.label_15, 1, 2, 1, 1)
        self.name_recording_line_edit = QtWidgets.QLineEdit(self.Recording_tab)
        self.name_recording_line_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.name_recording_line_edit.setText("")
        self.name_recording_line_edit.setObjectName("name_recording_line_edit")
        self.gridLayout_19.addWidget(self.name_recording_line_edit, 1, 3, 1, 1)
        self.Tab.addTab(self.Recording_tab, "")
        self.Generate_tab = QtWidgets.QWidget()
        self.Generate_tab.setObjectName("Generate_tab")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.Generate_tab)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_26 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.frame_26)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22)
        self.load_EE_rec_radio_button = QtWidgets.QRadioButton(self.frame_26)
        self.load_EE_rec_radio_button.setObjectName("load_EE_rec_radio_button")
        self.verticalLayout_15.addWidget(self.load_EE_rec_radio_button)
        self.load_JS_rec_radio_button = QtWidgets.QRadioButton(self.frame_26)
        self.load_JS_rec_radio_button.setObjectName("load_JS_rec_radio_button")
        self.verticalLayout_15.addWidget(self.load_JS_rec_radio_button)
        self.gridLayout_20.addWidget(self.frame_26, 0, 0, 1, 1)
        self.frame_24 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.splitter_13 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.label_16 = QtWidgets.QLabel(self.splitter_13)
        self.label_16.setObjectName("label_16")
        self.dmp_dt_param_lineedit = QtWidgets.QLineEdit(self.splitter_13)
        self.dmp_dt_param_lineedit.setObjectName("dmp_dt_param_lineedit")
        self.verticalLayout_13.addWidget(self.splitter_13)
        self.splitter_14 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.label_17 = QtWidgets.QLabel(self.splitter_14)
        self.label_17.setObjectName("label_17")
        self.dmp_K_param_lineedit = QtWidgets.QLineEdit(self.splitter_14)
        self.dmp_K_param_lineedit.setObjectName("dmp_K_param_lineedit")
        self.verticalLayout_13.addWidget(self.splitter_14)
        self.splitter_15 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.label_18 = QtWidgets.QLabel(self.splitter_15)
        self.label_18.setObjectName("label_18")
        self.dmp_D_param_lineedit = QtWidgets.QLineEdit(self.splitter_15)
        self.dmp_D_param_lineedit.setObjectName("dmp_D_param_lineedit")
        self.verticalLayout_13.addWidget(self.splitter_15)
        self.splitter_16 = QtWidgets.QSplitter(self.frame_24)
        self.splitter_16.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_16.setObjectName("splitter_16")
        self.label_19 = QtWidgets.QLabel(self.splitter_16)
        self.label_19.setObjectName("label_19")
        self.dmp_basisfunc_param_lineedit = QtWidgets.QLineEdit(self.splitter_16)
        self.dmp_basisfunc_param_lineedit.setObjectName("dmp_basisfunc_param_lineedit")
        self.verticalLayout_13.addWidget(self.splitter_16)
        self.gridLayout_20.addWidget(self.frame_24, 1, 0, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.splitter_17 = QtWidgets.QSplitter(self.frame_25)
        self.splitter_17.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_17.setObjectName("splitter_17")
        self.label_20 = QtWidgets.QLabel(self.splitter_17)
        self.label_20.setObjectName("label_20")
        self.load_name_rec_comboBox = QtWidgets.QComboBox(self.splitter_17)
        self.load_name_rec_comboBox.setEditable(True)
        self.load_name_rec_comboBox.setObjectName("load_name_rec_comboBox")
        self.verticalLayout_14.addWidget(self.splitter_17)
        self.splitter_18 = QtWidgets.QSplitter(self.frame_25)
        self.splitter_18.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_18.setObjectName("splitter_18")
        self.label_21 = QtWidgets.QLabel(self.splitter_18)
        self.label_21.setObjectName("label_21")
        self.save_name_dmp_lineedit = QtWidgets.QLineEdit(self.splitter_18)
        self.save_name_dmp_lineedit.setObjectName("save_name_dmp_lineedit")
        self.verticalLayout_14.addWidget(self.splitter_18)
        self.gridLayout_20.addWidget(self.frame_25, 2, 0, 1, 1)
        self.frame_27 = QtWidgets.QFrame(self.Generate_tab)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.generate_DMP_button = QtWidgets.QPushButton(self.frame_27)
        self.generate_DMP_button.setObjectName("generate_DMP_button")
        self.verticalLayout_16.addWidget(self.generate_DMP_button)
        self.gridLayout_20.addWidget(self.frame_27, 3, 0, 1, 1)
        self.Tab.addTab(self.Generate_tab, "")
        self.Execute_tab = QtWidgets.QWidget()
        self.Execute_tab.setObjectName("Execute_tab")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.Execute_tab)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.frame_28 = QtWidgets.QFrame(self.Execute_tab)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_29)
        self.splitter_3.setGeometry(QtCore.QRect(10, 10, 278, 25))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_23 = QtWidgets.QLabel(self.splitter_3)
        self.label_23.setObjectName("label_23")
        self.set_DMP_comboBox = QtWidgets.QComboBox(self.splitter_3)
        self.set_DMP_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.set_DMP_comboBox.setObjectName("set_DMP_comboBox")
        self.set_active_DMP_pushButton = QtWidgets.QPushButton(self.splitter_3)
        self.set_active_DMP_pushButton.setObjectName("set_active_DMP_pushButton")
        self.gridLayout_7.addWidget(self.frame_29, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_28)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_5)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_6.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 0, 1, 3, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_28)
        self.tabWidget.setObjectName("tabWidget")
        self.jointspace_2 = QtWidgets.QWidget()
        self.jointspace_2.setObjectName("jointspace_2")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.jointspace_2)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.frame_32 = QtWidgets.QFrame(self.jointspace_2)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_32)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.set_JointState_init_0_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_0_lineEdit.setObjectName("set_JointState_init_0_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_0_lineEdit, 1, 0, 1, 1)
        self.set_JointState_init_2_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_2_lineEdit.setObjectName("set_JointState_init_2_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_2_lineEdit, 3, 0, 1, 1)
        self.set_JointState_init_5_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_5_lineEdit.setObjectName("set_JointState_init_5_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_5_lineEdit, 6, 0, 1, 1)
        self.set_JointState_init_1_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_1_lineEdit.setObjectName("set_JointState_init_1_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_1_lineEdit, 2, 0, 1, 1)
        self.set_JointState_init_3_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_3_lineEdit.setObjectName("set_JointState_init_3_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_3_lineEdit, 4, 0, 1, 1)
        self.get_JS_init_robot_pushButton = QtWidgets.QPushButton(self.frame_32)
        self.get_JS_init_robot_pushButton.setObjectName("get_JS_init_robot_pushButton")
        self.gridLayout_25.addWidget(self.get_JS_init_robot_pushButton, 7, 0, 1, 1)
        self.set_JointState_init_4_lineEdit = QtWidgets.QLineEdit(self.frame_32)
        self.set_JointState_init_4_lineEdit.setObjectName("set_JointState_init_4_lineEdit")
        self.gridLayout_25.addWidget(self.set_JointState_init_4_lineEdit, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_32)
        self.label_25.setObjectName("label_25")
        self.gridLayout_25.addWidget(self.label_25, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_32, 0, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(self.jointspace_2)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_33)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.set_JointState_goal_1_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_1_lineEdit.setObjectName("set_JointState_goal_1_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_1_lineEdit, 2, 0, 1, 1)
        self.get_JS_goal_robot_pushButton = QtWidgets.QPushButton(self.frame_33)
        self.get_JS_goal_robot_pushButton.setObjectName("get_JS_goal_robot_pushButton")
        self.gridLayout_26.addWidget(self.get_JS_goal_robot_pushButton, 7, 0, 1, 1)
        self.set_JointState_goal_4_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_4_lineEdit.setObjectName("set_JointState_goal_4_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_4_lineEdit, 5, 0, 1, 1)
        self.set_JointState_goal_3_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_3_lineEdit.setObjectName("set_JointState_goal_3_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_3_lineEdit, 4, 0, 1, 1)
        self.set_JointState_goal_0_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_0_lineEdit.setObjectName("set_JointState_goal_0_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_0_lineEdit, 1, 0, 1, 1)
        self.set_JointState_goal_5_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_5_lineEdit.setObjectName("set_JointState_goal_5_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_5_lineEdit, 6, 0, 1, 1)
        self.set_JointState_goal_2_lineEdit = QtWidgets.QLineEdit(self.frame_33)
        self.set_JointState_goal_2_lineEdit.setObjectName("set_JointState_goal_2_lineEdit")
        self.gridLayout_26.addWidget(self.set_JointState_goal_2_lineEdit, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_33)
        self.label_26.setObjectName("label_26")
        self.gridLayout_26.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.frame_33, 0, 1, 1, 1)
        self.tabWidget.addTab(self.jointspace_2, "")
        self.cartesianSpace_2 = QtWidgets.QWidget()
        self.cartesianSpace_2.setObjectName("cartesianSpace_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.cartesianSpace_2)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.frame_34 = QtWidgets.QFrame(self.cartesianSpace_2)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.frame_34)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_28.addWidget(self.lineEdit_50, 3, 0, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_28.addWidget(self.lineEdit_51, 7, 0, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_28.addWidget(self.lineEdit_52, 2, 0, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_28.addWidget(self.lineEdit_53, 4, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_34)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_28.addWidget(self.pushButton_15, 8, 0, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_28.addWidget(self.lineEdit_54, 6, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_34)
        self.label_27.setObjectName("label_27")
        self.gridLayout_28.addWidget(self.label_27, 0, 0, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_28.addWidget(self.lineEdit_55, 1, 0, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.frame_34)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_28.addWidget(self.lineEdit_56, 5, 0, 1, 1)
        self.gridLayout_27.addWidget(self.frame_34, 0, 0, 1, 1)
        self.frame_35 = QtWidgets.QFrame(self.cartesianSpace_2)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_35)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_29.addWidget(self.lineEdit_57, 1, 0, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_29.addWidget(self.lineEdit_58, 2, 0, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_29.addWidget(self.lineEdit_59, 4, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_35)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_29.addWidget(self.pushButton_16, 8, 0, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout_29.addWidget(self.lineEdit_60, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_35)
        self.label_28.setObjectName("label_28")
        self.gridLayout_29.addWidget(self.label_28, 0, 0, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_29.addWidget(self.lineEdit_61, 7, 0, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_29.addWidget(self.lineEdit_62, 3, 0, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.frame_35)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_29.addWidget(self.lineEdit_63, 5, 0, 1, 1)
        self.gridLayout_27.addWidget(self.frame_35, 0, 1, 1, 1)
        self.tabWidget.addTab(self.cartesianSpace_2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.frame_28)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_36 = QtWidgets.QFrame(self.frame_31)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_36)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.execute_plan_pushButton = QtWidgets.QPushButton(self.frame_36)
        self.execute_plan_pushButton.setObjectName("execute_plan_pushButton")
        self.gridLayout_30.addWidget(self.execute_plan_pushButton, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_36, 1, 0, 1, 1)
        self.frame_30 = QtWidgets.QFrame(self.frame_31)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.splitter_4 = QtWidgets.QSplitter(self.frame_30)
        self.splitter_4.setGeometry(QtCore.QRect(10, 10, 300, 25))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_24 = QtWidgets.QLabel(self.splitter_4)
        self.label_24.setObjectName("label_24")
        self.set_tau_lineedit = QtWidgets.QLineEdit(self.splitter_4)
        self.set_tau_lineedit.setMaximumSize(QtCore.QSize(16777215, 28))
        self.set_tau_lineedit.setObjectName("set_tau_lineedit")
        self.get_DMP_Plan_pushButton = QtWidgets.QPushButton(self.splitter_4)
        self.get_DMP_Plan_pushButton.setObjectName("get_DMP_Plan_pushButton")
        self.gridLayout_23.addWidget(self.frame_30, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_31, 2, 0, 1, 1)
        self.gridLayout_31.addWidget(self.frame_28, 0, 1, 1, 1)
        self.Tab.addTab(self.Execute_tab, "")
        self.Settings_tab = QtWidgets.QWidget()
        self.Settings_tab.setObjectName("Settings_tab")
        self.Tab.addTab(self.Settings_tab, "")
        self.gridLayout_13.addWidget(self.splitter_12, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_21, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.Tab.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Welcome to this robot DMP application.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Author: Roy Ove Eriksen</p></body></html>"))
        self.RobotIPLabel.setText(_translate("MainWindow", "Robot IP:"))
        self.IPLineEdit.setPlaceholderText(_translate("MainWindow", "192.168.1.128"))
        self.simulationCheckBox.setText(_translate("MainWindow", "Simulation"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.shutDownButton.setText(_translate("MainWindow", "Shutdown"))
        self.ChooseRobotcomboBox.setItemText(0, _translate("MainWindow", "UR3"))
        self.ChooseRobotcomboBox.setItemText(1, _translate("MainWindow", "UR5"))
        self.ChooseRobotcomboBox.setItemText(2, _translate("MainWindow", "UR10"))
        self.start_recording_button.setText(_translate("MainWindow", "Start"))
        self.stop_recording_button.setText(_translate("MainWindow", "Stop"))
        self.rec_EE_radio_button.setText(_translate("MainWindow", "End-Effector"))
        self.rec_JS_radio_button.setText(_translate("MainWindow", "Joint_States"))
        self.rec_JS_Filter_radio_button.setText(_translate("MainWindow", "Joint_States with filtering"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.Tab.setTabText(self.Tab.indexOf(self.Recording_tab), _translate("MainWindow", "Recording"))
        self.label_22.setText(_translate("MainWindow", "Type of recording to load"))
        self.load_EE_rec_radio_button.setText(_translate("MainWindow", "End-Effector rec"))
        self.load_JS_rec_radio_button.setText(_translate("MainWindow", "Joint_state rec"))
        self.label_16.setText(_translate("MainWindow", "dt"))
        self.dmp_dt_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 0.008"))
        self.label_17.setText(_translate("MainWindow", "K"))
        self.dmp_K_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 100"))
        self.label_18.setText(_translate("MainWindow", "D"))
        self.dmp_D_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 1"))
        self.label_19.setText(_translate("MainWindow", "# basis_func"))
        self.dmp_basisfunc_param_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 120"))
        self.label_20.setText(_translate("MainWindow", "name of recording"))
        self.label_21.setText(_translate("MainWindow", "name of output file"))
        self.save_name_dmp_lineedit.setPlaceholderText(_translate("MainWindow", "ex: recording_start_goal_with"))
        self.generate_DMP_button.setText(_translate("MainWindow", "Generate DMP"))
        self.Tab.setTabText(self.Tab.indexOf(self.Generate_tab), _translate("MainWindow", "Learning"))
        self.label_23.setText(_translate("MainWindow", "Set active DMP"))
        self.set_active_DMP_pushButton.setText(_translate("MainWindow", "PushButton"))
        self.set_JointState_init_0_lineEdit.setPlaceholderText(_translate("MainWindow", "(-pi, pi)"))
        self.get_JS_init_robot_pushButton.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.label_25.setText(_translate("MainWindow", "Initial position"))
        self.get_JS_goal_robot_pushButton.setText(_translate("MainWindow", "Retrieve from robot"))
        self.label_26.setText(_translate("MainWindow", "Goal Position"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.jointspace_2), _translate("MainWindow", "Joint space"))
        self.pushButton_15.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.label_27.setText(_translate("MainWindow", "Initial Pose"))
        self.pushButton_16.setText(_translate("MainWindow", "Retrieve from Robot"))
        self.label_28.setText(_translate("MainWindow", "Goal Pose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cartesianSpace_2), _translate("MainWindow", "Cartesian Space"))
        self.execute_plan_pushButton.setText(_translate("MainWindow", "EXECUTE PLAN"))
        self.label_24.setText(_translate("MainWindow", "tau"))
        self.set_tau_lineedit.setPlaceholderText(_translate("MainWindow", "Default: 5"))
        self.get_DMP_Plan_pushButton.setText(_translate("MainWindow", "Retrieve DMP plan"))
        self.Tab.setTabText(self.Tab.indexOf(self.Execute_tab), _translate("MainWindow", "Execute"))
        self.Tab.setTabText(self.Tab.indexOf(self.Settings_tab), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

